// SPDX-License-Identifier: PMPL-1.0-or-later
//
// tests/e2e_test.rs — End-to-end pipeline tests for patch-bridge.
//
// Tests the full classify → intelligence → reachability pipeline using
// synthetic lockfile content and in-memory project directory fixtures.

use patch_bridge::bridge::{
    classify::classify,
    lockfile::parse_cargo_lock,
    reachability::check_reachability,
    Classification, ImportSite, LockedDependency, ReachabilityEvidence, ReachabilityStatus,
    SeverityLabel, SourceTier, Vulnerability,
};
use std::io::Write;
use std::path::PathBuf;
use tempfile::TempDir;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Build a synthetic Vulnerability struct for testing.
fn make_vuln(package: &str, version: &str, has_fix: bool, semver: bool) -> Vulnerability {
    Vulnerability {
        id: format!("RUSTSEC-2026-{:04}", package.len()),
        cve: Some("CVE-2026-99999".to_string()),
        summary: format!("Test advisory for {}", package),
        package: package.to_string(),
        version: version.to_string(),
        severity: Some(8.0),
        severity_label: SeverityLabel::High,
        fixed_versions: if has_fix {
            vec!["2.0.0".to_string()]
        } else {
            vec![]
        },
        semver_fix_available: semver,
        source_tier: SourceTier::Tier1,
        references: vec!["https://rustsec.org/advisories/RUSTSEC-2026-0001.html".to_string()],
    }
}

/// Create a temporary project directory with a Cargo.lock and optional src/ files.
fn setup_project(cargo_lock_content: &str, src_files: &[(&str, &str)]) -> TempDir {
    let tmp = TempDir::new().expect("Failed to create temp dir");
    std::fs::write(tmp.path().join("Cargo.lock"), cargo_lock_content)
        .expect("Failed to write Cargo.lock");

    if !src_files.is_empty() {
        let src_dir = tmp.path().join("src");
        std::fs::create_dir_all(&src_dir).expect("Failed to create src dir");
        for (name, content) in src_files {
            std::fs::write(src_dir.join(name), content).expect("Failed to write src file");
        }
    }
    tmp
}

/// Minimal valid Cargo.lock containing a single registry dependency.
fn cargo_lock_with_dep(name: &str, version: &str) -> String {
    format!(
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n\
         [[package]]\nname = \"{}\"\nversion = \"{}\"\n\
         source = \"registry+https://github.com/rust-lang/crates.io-index\"\n\
         checksum = \"abc123\"\n",
        name, version
    )
}

// ---------------------------------------------------------------------------
// E2E: lockfile parsing pipeline
// ---------------------------------------------------------------------------

#[test]
fn e2e_lockfile_parse_single_registry_dep() {
    let tmp = setup_project(&cargo_lock_with_dep("serde", "1.0.200"), &[]);
    let deps = parse_cargo_lock(&tmp.path().join("Cargo.lock"))
        .expect("parse_cargo_lock must succeed");
    assert_eq!(deps.len(), 1, "Expected exactly one dependency");
    assert_eq!(deps[0].name, "serde");
    assert_eq!(deps[0].version, "1.0.200");
    assert_eq!(deps[0].ecosystem, "crates.io");
}

#[test]
fn e2e_lockfile_parse_multiple_deps() {
    let lock = format!(
        "# Generated by Cargo.\nversion = 4\n\n{}{}",
        cargo_lock_with_dep("serde", "1.0.200"),
        cargo_lock_with_dep("anyhow", "1.0.86"),
    );
    let tmp = setup_project(&lock, &[]);
    let deps = parse_cargo_lock(&tmp.path().join("Cargo.lock"))
        .expect("parse_cargo_lock must succeed");
    assert_eq!(deps.len(), 2, "Expected two dependencies");
}

#[test]
fn e2e_lockfile_skips_local_packages_without_source() {
    let lock = "[[package]]\nname = \"my-project\"\nversion = \"0.1.0\"\n";
    let tmp = setup_project(lock, &[]);
    let deps = parse_cargo_lock(&tmp.path().join("Cargo.lock"))
        .expect("parse_cargo_lock must succeed");
    assert!(deps.is_empty(), "Local packages with no registry source must be skipped");
}

// ---------------------------------------------------------------------------
// E2E: reachability pipeline
// ---------------------------------------------------------------------------

#[test]
fn e2e_reachability_phantom_dep_not_imported() {
    let tmp = setup_project(
        &cargo_lock_with_dep("octocrab", "0.39.0"),
        &[("main.rs", "use serde::Serialize;\nfn main() {}\n")],
    );
    let evidence = check_reachability(tmp.path(), "octocrab")
        .expect("check_reachability must succeed");
    assert!(!evidence.is_imported, "octocrab is not imported — must be phantom");
    assert_eq!(evidence.status, ReachabilityStatus::Phantom);
    assert!(evidence.import_sites.is_empty());
}

#[test]
fn e2e_reachability_imported_dep_is_reachable() {
    let tmp = setup_project(
        &cargo_lock_with_dep("serde", "1.0.200"),
        &[("lib.rs", "use serde::Serialize;\n\npub struct Foo;\n")],
    );
    let evidence = check_reachability(tmp.path(), "serde")
        .expect("check_reachability must succeed");
    assert!(evidence.is_imported, "serde is imported — must be reachable");
    assert_eq!(evidence.status, ReachabilityStatus::Reachable);
    assert!(!evidence.import_sites.is_empty());
}

#[test]
fn e2e_reachability_hyphenated_crate_name_normalised() {
    let tmp = setup_project(
        &cargo_lock_with_dep("serde-json", "1.0.117"),
        &[("main.rs", "use serde_json::Value;\nfn main() {}\n")],
    );
    let evidence = check_reachability(tmp.path(), "serde-json")
        .expect("check_reachability must succeed for hyphenated name");
    assert!(evidence.is_imported, "serde-json (normalised to serde_json) must be detected");
}

// ---------------------------------------------------------------------------
// E2E: classify pipeline
// ---------------------------------------------------------------------------

#[test]
fn e2e_classify_phantom_dep_gives_informational() {
    let vuln = make_vuln("unused-crate", "1.0.0", false, false);
    let evidence = ReachabilityEvidence {
        is_imported: false,
        import_sites: vec![],
        status: ReachabilityStatus::Phantom,
    };
    let (cls, rationale, action) = classify(&vuln, &evidence);
    assert_eq!(cls, Classification::Informational);
    assert!(rationale.contains("unused-crate"), "Rationale must mention package name");
    assert!(action.contains("Remove"), "Action must suggest removing the dep");
}

#[test]
fn e2e_classify_reachable_no_fix_gives_unmitigable() {
    let vuln = make_vuln("dangerous-dep", "1.0.0", false, false);
    let evidence = ReachabilityEvidence {
        is_imported: true,
        import_sites: vec![ImportSite {
            file: PathBuf::from("src/main.rs"),
            line: 1,
            statement: "use dangerous_dep::Api;".to_string(),
        }],
        status: ReachabilityStatus::Reachable,
    };
    let (cls, _rationale, _action) = classify(&vuln, &evidence);
    assert_eq!(cls, Classification::Unmitigable);
}

#[test]
fn e2e_classify_reachable_with_semver_fix_gives_mitigable() {
    let vuln = make_vuln("fixable-dep", "1.0.0", true, true);
    let evidence = ReachabilityEvidence {
        is_imported: true,
        import_sites: vec![ImportSite {
            file: PathBuf::from("src/lib.rs"),
            line: 3,
            statement: "use fixable_dep::Thing;".to_string(),
        }],
        status: ReachabilityStatus::Reachable,
    };
    let (cls, _rationale, action) = classify(&vuln, &evidence);
    assert_eq!(cls, Classification::Mitigable);
    assert!(action.contains("cargo update"), "Action must suggest cargo update for semver fix");
}

#[test]
fn e2e_classify_reachable_with_breaking_fix_gives_mitigable_with_breaking_action() {
    let vuln = make_vuln("breaking-dep", "1.0.0", true, false);
    let evidence = ReachabilityEvidence {
        is_imported: true,
        import_sites: vec![ImportSite {
            file: PathBuf::from("src/api.rs"),
            line: 10,
            statement: "use breaking_dep::Client;".to_string(),
        }],
        status: ReachabilityStatus::Reachable,
    };
    let (cls, _rationale, action) = classify(&vuln, &evidence);
    assert_eq!(cls, Classification::Mitigable);
    assert!(action.contains("breaking change"), "Action must warn about breaking change");
}

#[test]
fn e2e_full_pipeline_lockfile_to_classification() {
    // Simulate: parse lockfile → determine dep → classify as phantom (not imported)
    let tmp = setup_project(
        &cargo_lock_with_dep("orphaned", "0.5.0"),
        &[("main.rs", "// No imports of orphaned here\nfn main() {}\n")],
    );
    let deps = parse_cargo_lock(&tmp.path().join("Cargo.lock"))
        .expect("lockfile parse must succeed");
    assert!(!deps.is_empty(), "Must find orphaned dep in lockfile");

    let dep = &deps[0];
    let evidence = check_reachability(tmp.path(), &dep.name)
        .expect("reachability check must succeed");
    assert_eq!(evidence.status, ReachabilityStatus::Phantom, "Unimported dep must be phantom");

    let vuln = make_vuln(&dep.name, &dep.version, false, false);
    let (cls, _rationale, _action) = classify(&vuln, &evidence);
    assert_eq!(cls, Classification::Informational, "Phantom dep must classify as Informational");
}
