// SPDX-License-Identifier: PMPL-1.0-or-later

//! Cargo.lock parser — extracts dependencies with versions.
//!
//! Parses the TOML-based Cargo.lock format to produce a list of
//! LockedDependency structs for CVE feed queries.

use super::LockedDependency;
use anyhow::{Context, Result};
use std::path::Path;

/// Parse a Cargo.lock file into a list of locked dependencies.
///
/// Handles Cargo.lock v3 format (the current default). Each `[[package]]`
/// entry becomes a LockedDependency. We skip the root package (source = None
/// and no registry source) since it's the project itself, not a dependency.
pub fn parse_cargo_lock(path: &Path) -> Result<Vec<LockedDependency>> {
    let content = std::fs::read_to_string(path)
        .with_context(|| format!("Failed to read {}", path.display()))?;

    let mut deps = Vec::new();
    let mut current_name: Option<String> = None;
    let mut current_version: Option<String> = None;
    let mut current_source: Option<String> = None;

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed == "[[package]]" {
            // Flush previous package if it was a registry dependency
            if let (Some(name), Some(version)) = (current_name.take(), current_version.take()) {
                if current_source.as_ref().map_or(false, |s| s.contains("registry")) {
                    deps.push(LockedDependency {
                        name,
                        version,
                        ecosystem: "crates.io".to_string(),
                        declared_by: Vec::new(),
                    });
                }
            }
            current_name = None;
            current_version = None;
            current_source = None;
            continue;
        }

        if let Some(rest) = trimmed.strip_prefix("name = ") {
            current_name = Some(unquote(rest));
        } else if let Some(rest) = trimmed.strip_prefix("version = ") {
            current_version = Some(unquote(rest));
        } else if let Some(rest) = trimmed.strip_prefix("source = ") {
            current_source = Some(unquote(rest));
        }
    }

    // Flush last package
    if let (Some(name), Some(version)) = (current_name, current_version) {
        if current_source.as_ref().map_or(false, |s| s.contains("registry")) {
            deps.push(LockedDependency {
                name,
                version,
                ecosystem: "crates.io".to_string(),
                declared_by: Vec::new(),
            });
        }
    }

    Ok(deps)
}

/// Remove surrounding quotes from a TOML value string.
fn unquote(s: &str) -> String {
    s.trim().trim_matches('"').to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    #[test]
    fn test_parse_cargo_lock_basic() {
        let mut tmp = tempfile::NamedTempFile::new().expect("TODO: handle error");
        write!(
            tmp,
            r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "my-project"
version = "0.1.0"

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc123"

[[package]]
name = "anyhow"
version = "1.0.86"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "def456"
"#
        )
        .expect("TODO: handle error");

        let deps = parse_cargo_lock(tmp.path()).expect("TODO: handle error");
        assert_eq!(deps.len(), 2);
        assert_eq!(deps[0].name, "serde");
        assert_eq!(deps[0].version, "1.0.200");
        assert_eq!(deps[0].ecosystem, "crates.io");
        assert_eq!(deps[1].name, "anyhow");
    }

    #[test]
    fn test_skips_local_packages() {
        let mut tmp = tempfile::NamedTempFile::new().expect("TODO: handle error");
        write!(
            tmp,
            r#"[[package]]
name = "my-local-dep"
version = "0.1.0"
"#
        )
        .expect("TODO: handle error");

        let deps = parse_cargo_lock(tmp.path()).expect("TODO: handle error");
        assert!(deps.is_empty(), "Local packages (no source) should be skipped");
    }
}
